// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconv2d_accel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConv2d_accel_CfgInitialize(XConv2d_accel *InstancePtr, XConv2d_accel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConv2d_accel_Start(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL) & 0x80;
    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConv2d_accel_IsDone(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConv2d_accel_IsIdle(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConv2d_accel_IsReady(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConv2d_accel_EnableAutoRestart(XConv2d_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XConv2d_accel_DisableAutoRestart(XConv2d_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_AP_CTRL, 0);
}

void XConv2d_accel_Set_input_V(XConv2d_accel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_INPUT_V_DATA, Data);
}

u32 XConv2d_accel_Get_input_V(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_INPUT_V_DATA);
    return Data;
}

void XConv2d_accel_Set_kernel_V(XConv2d_accel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_KERNEL_V_DATA, Data);
}

u32 XConv2d_accel_Get_kernel_V(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_KERNEL_V_DATA);
    return Data;
}

void XConv2d_accel_Set_bias_V(XConv2d_accel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_BIAS_V_DATA, Data);
}

u32 XConv2d_accel_Get_bias_V(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_BIAS_V_DATA);
    return Data;
}

void XConv2d_accel_Set_output_V(XConv2d_accel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_OUTPUT_V_DATA, Data);
}

u32 XConv2d_accel_Get_output_V(XConv2d_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_OUTPUT_V_DATA);
    return Data;
}

void XConv2d_accel_InterruptGlobalEnable(XConv2d_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_GIE, 1);
}

void XConv2d_accel_InterruptGlobalDisable(XConv2d_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_GIE, 0);
}

void XConv2d_accel_InterruptEnable(XConv2d_accel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_IER);
    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_IER, Register | Mask);
}

void XConv2d_accel_InterruptDisable(XConv2d_accel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_IER);
    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_IER, Register & (~Mask));
}

void XConv2d_accel_InterruptClear(XConv2d_accel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv2d_accel_WriteReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_ISR, Mask);
}

u32 XConv2d_accel_InterruptGetEnabled(XConv2d_accel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_IER);
}

u32 XConv2d_accel_InterruptGetStatus(XConv2d_accel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConv2d_accel_ReadReg(InstancePtr->Control_BaseAddress, XCONV2D_ACCEL_CONTROL_ADDR_ISR);
}

